CREATE OR REPLACE FUNCTION test_000_basic_tbl005_usim_planck_tick()
  RETURNS SETOF TEXT
  LANGUAGE 'plpgsql'
AS $BODY$
  DECLARE
    l_bda_id  character(32);
    l_pla_id  character(32);
    l_pla_add bigint;
  BEGIN
    -- no column check already done on constraint check
    RETURN NEXT can('usim_test', ARRAY['plt_fn_ins_trg', 'plt_fn_upd_trg'], 'Check usim_planck_tick trigger functions');

  END;
$BODY$;
