ACCEPT PASSW CHAR PROMPT 'Password for user USIM: '
CREATE USER usim IDENTIFIED BY &PASSW;

ALTER USER usim
DEFAULT TABLESPACE usim_live
ACCOUNT UNLOCK;

-- QUOTAS
ALTER USER usim QUOTA UNLIMITED ON usim_live;

-- ROLES
-- basic roles
GRANT GATHER_SYSTEM_STATISTICS, CONNECT, RESOURCE TO usim;

-- privileges
GRANT CREATE VIEW TO usim;
GRANT ALL ON DIRECTORY usim_dir TO usim;
GRANT ALL ON DIRECTORY usim_hist_dir TO usim;
GRANT EXECUTE ON UTL_FILE to usim;
GRANT EXECUTE ON DBMS_LOB to usim;
