ACCEPT PASSW CHAR PROMPT 'Password for user USIM: '
CREATE USER usim IDENTIFIED BY &PASSW;

ALTER USER usim
DEFAULT TABLESPACE usim_live
ACCOUNT UNLOCK;

-- QUOTAS
ALTER USER usim QUOTA UNLIMITED ON usim_live;

-- ROLES
-- basic roles
GRANT GATHER_SYSTEM_STATISTICS, CONNECT, RESOURCE TO usim;
