ACCEPT PASSW CHAR PROMPT 'Password for user USIM_TEST: '
CREATE USER usim_test IDENTIFIED BY &PASSW;

ALTER USER usim_test
DEFAULT TABLESPACE usim_test
ACCOUNT UNLOCK;

-- QUOTAS
ALTER USER usim_test QUOTA UNLIMITED ON usim_test;

-- ROLES
-- basic roles
GRANT GATHER_SYSTEM_STATISTICS, CONNECT, RESOURCE TO usim_test;
