-- setup or recreate usim and usim test
-- TRIGGERS ARE NOT DELETED ON CASCADE !!!!
-- session informations
SELECT current_schema AS var_schema
\gset
\echo 'Setting up schema USIM. DB schema: ' || :var_schema
\echo 'Cleanup objects for USim model'
\i /usim_src/SETUP/USimCleanup.psql
\echo 'Create objects for USim model'
\i /usim_src/SETUP/USimModel.psql
-- display objects installed
SELECT * FROM public.pg_objects WHERE obj_owner = current_user AND obj_schema = current_schema;
