-- views
\echo 'Dropping USim View usim_bda_active_v'
\i /usim_src/VIEW/DROP/drop_usim_bda_active_v.psql
\echo 'Dropping USim View usim_bda_v'
\i /usim_src/VIEW/DROP/drop_usim_bda_v.psql
-- tables and depending objects
\echo 'Dropping USim Table usim_position and depending objects'
\i /usim_src/TABLES/DROP/drop_usim_position_tbl.psql
\echo 'Dropping USim Table usim_dimension and depending objects'
\i /usim_src/TABLES/DROP/drop_usim_dimension_tbl.psql
\echo 'Dropping USim Table usim_multiverse and depending objects'
\i /usim_src/TABLES/DROP/drop_usim_multiverse_tbl.psql
\echo 'Dropping USim Table usim_planck_tick and depending objects'
\i /usim_src/TABLES/DROP/drop_usim_planck_tick_tbl.psql
\echo 'Dropping USim Table usim_planck_aeon and depending objects'
\i /usim_src/TABLES/DROP/drop_usim_planck_aeon_tbl.psql
\echo 'Dropping USim Table usim_bda_state and depending objects'
\i /usim_src/TABLES/DROP/drop_usim_bda_state_tbl.psql
\echo 'Dropping USim Table usim_basedata and depending objects'
\i /usim_src/TABLES/DROP/drop_usim_basedata_tbl.psql
\echo 'Dropping USim Table usim_sequences and depending objects'
\i /usim_src/TABLES/DROP/drop_usim_sequences.psql
-- functions
\echo 'Dropping USim Function usim_create_id'
\i /usim_src/FUNCTIONS/DROP/drop_usim_create_id.psql
\echo 'Dropping USim Function usim_int_to_id'
\i /usim_src/FUNCTIONS/DROP/drop_usim_int_to_id.psql
\echo 'Dropping USim Function usim_bigint_def'
\i /usim_src/FUNCTIONS/DROP/drop_usim_bigint_def.psql
-- procedures
\echo 'Dropping USim Procedure bda_new_sim'
\i /usim_src/PROCEDURES/DROP/drop_bda_new_sim.psql
-- test functions
\echo 'Dropping USim test function test_000_basic_schema'
\i /usim_src/TESTING/DROP/drop_test_000_basic_app_schema.psql
\echo 'Dropping USim test function test_000_basic_fn001_usim_create_id'
\i /usim_src/TESTING/DROP/drop_test_000_basic_fn001_usim_create_id.psql
\echo 'Dropping USim test function test_000_basic_fn002_usim_bigint_def'
\i /usim_src/TESTING/DROP/drop_test_000_basic_fn002_usim_bigint_def.psql

-- list objects remaining
\echo 'Remaining USim Objects'
SELECT * FROM public.pg_objects WHERE obj_owner = current_user AND obj_schema = current_schema;
