-- default settings for spooling log files
SET ECHO ON
SET VERIFY ON
SET TRIMSPOOL ON
SET LINESIZE 1000
SET PAGESIZE 2000
SET FEEDBACK ON
SET NULL 'NULL'
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT FAILURE ROLLBACK
WHENEVER OSERROR EXIT FAILURE ROLLBACK
CLEAR COLUMNS
-- used for setting script file names to execute
COLUMN SCRIPTFILE NEW_VAL SCRIPTFILE
-- used for setting log file names to spool
COLUMN LOGFILE NEW_VAL LOGFILE

