-- default settings for spooling log files
SET ECHO OFF
SET VERIFY OFF
SET TRIMSPOOL ON
SET LINESIZE 9999
SET PAGESIZE 9999
SET FEEDBACK ON
SET NULL 'NULL'
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
WHENEVER OSERROR EXIT -1 ROLLBACK
CLEAR COLUMNS
-- used for setting script file names to execute
COLUMN SCRIPTFILE NEW_VAL SCRIPTFILE
-- used for setting log file names to spool
COLUMN LOGFILE NEW_VAL LOGFILE

